<!DOCTYPE html><!--if lt IE 7html.no-js.lt-ie9.lt-ie8.lt-ie7(lang='en')  --><!--if IE 7html.no-js.lt-ie9.lt-ie8(lang='en')  --><!--if IE 8html.no-js.lt-ie9(lang='en')  --><!-- [if gt IE 8] <!--><html lang="en" class="no-js"><!-- <![endif]--><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><?= $tpl_header; ?><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="apple-touch-icon" href="apple-touch-icon.png"><link rel="stylesheet" href="css/main.css"><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"><link href="http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Raleway:400,500,600,700,800,900" rel="stylesheet" type="text/css"><script src="js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script></head><body><!--if lt IE 8p.browserupgrade
	| You are using an 
	strong outdated
	|  browser. Please 
	a(href='http://browsehappy.com/') upgrade your browser
	|  to improve your experience.
--><div class="top_line"></div><!-- HEADER AREA--><header><div class="container"><div class="row"><!-- HEADER: LOGO AREA--><div class="logo col-sm-4 col-md-4"><a href="index.html" class="logo"><img alt="logo" title="ReDesign" src="img/logo.png"></a></div><div class="col-lg-offset-4 col-sm-4 col-md-4"><!-- HEADER: PHONE NUMBER--><p class="head_phone"><i class="fa fa-phone"></i><a href="tel:555-555-5555">(800) 655-7800</a></p></div><!-- HEADER: SOCIAL ICONS--><ul class="socials list-unstyled"><li><a data-rel="tooltip" title="Follow us on Flickr" href="#" class="flickr"></a></li><li><a data-rel="tooltip" title="Follow us on Twitter" href="#" class="twitter"></a></li><li><a data-rel="tooltip" title="Follow us on Facebook" href="#" class="facebook"></a></li><li><a data-rel="tooltip" title="Follow us on Youtube" href="#" class="youtube"></a></li><li><a data-rel="tooltip" title="Follow us on Dribbble" href="#" class="dribbble"></a></li><li><a data-rel="tooltip" title="Follow us on Pinterest" href="#" class="pinterest"></a></li></ul></div></div></header><?= $tpl_content; ?><script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script><script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\\/script>')</script><script src="js/vendor/bootstrap.min.js"></script><script src="js/main.js"></script><!-- Google Analytics: change UA-XXXXX-X to be your site's ID.--><script>(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
e=o.createElement(i);r=o.getElementsByTagName(i)[0];
e.src='//www.google-analytics.com/analytics.js';
r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
ga('create','UA-XXXXX-X','auto');ga('send','pageview');</script></body></html>